# Generated by Django 4.2.7 on 2025-12-30 14:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0004_balancerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_method', models.CharField(help_text='Payment method (e.g., Bank, bKash, Nagad)', max_length=100)),
                ('payment_details', models.TextField(help_text='Payment details (account number, etc.)')),
                ('note', models.TextField(blank=True, help_text="User's note")),
                ('admin_note', models.TextField(blank=True, help_text="Admin's note for approval/rejection")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_cashout_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashout Request',
                'verbose_name_plural': 'Cashout Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
