# Generated by Django 4.2.7 on 2025-12-30 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_cashoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured/top-rated'),
        ),
        migrations.AddField(
            model_name='gig',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='gig',
            name='total_orders',
            field=models.IntegerField(default=0, help_text='Total completed orders'),
        ),
        migrations.AddField(
            model_name='gig',
            name='total_reviews',
            field=models.IntegerField(default=0, help_text='Total number of reviews'),
        ),
    ]
